# 1. Image Node.js
FROM node:24-alpine

# 2. Dossier de travail dans le conteneur
WORKDIR /app

# 3. Copier les fichiers de dépendances
COPY package*.json ./

# 4. Installer les dépendances
RUN npm install

# 5. Copier le code source
COPY . .

# 6. Exposer le port de l'application
EXPOSE 3001

# 7. Démarrer l'application
CMD ["npm", "start"]